exercises/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls"))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ExerciseIndex.as_view(), name="home"),
    path('about/', views.about, name='about'),
    path('exercises/', views.ExerciseIndex.as_view(), name='exercises_index'),
    path('exercises/<int:exercise_id>/details/', views.exercise_details, name='exercise_details'),
    path('exercises/create/', views.ExerciseCreate.as_view(), name='exercise_create'),
    path('exercises/<int:pk>/update/', views.ExerciseUpdate.as_view(), name='exercise_update'),
    path('exercises/<int:pk>/delete/', views.ExerciseDelete.as_view(), name='exercise_delete'),
    path('exercises/<int:exercise_id>/add_completion/', views.add_completion, name='add_completion'),
    path('exercises/<int:exercise_id>/add_photo/', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
 
# Create your models here.
class Exercise(models.Model):
    name = models.CharField(max_length=100)
    musclegroups = models.CharField('Muscle Groups', max_length=100)
    intensity = models.IntegerField()
    directions = models.TextField(max_length=500,)
    # completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('exercise_details', kwargs={'exercise_id': self.id})
    
class Completion(models.Model):
    date = models.DateField('Exercise Date')
    reps = models.IntegerField()
    sets = models.IntegerField()
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.date}, {self.reps}, {self.sets}, {self.exercise}"
    
    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for exercise: {self.exercise} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Completion

class CompletionForm(ModelForm):
    class Meta:
        model = Completion
        fields = ['date', 'reps', 'sets']

main_app/views.py
import os
import uuid
import boto3

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Exercise, Photo
from .forms import CompletionForm



# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


class ExerciseIndex(ListView):
    model = Exercise
    template_name = 'exercises/index.html'
    context_object_name = 'exercises'


def exercise_details(request, exercise_id):
    exercise = Exercise.objects.get(id=exercise_id)
    completion_form = CompletionForm()
    return render(request, 'exercises/details.html', {
        'exercise': exercise, 'completion_form': completion_form
    })


class ExerciseCreate(CreateView):
    model = Exercise
    fields = '__all__'


class ExerciseUpdate(UpdateView):
    model = Exercise
    fields = '__all__'


class ExerciseDelete(DeleteView):
    model = Exercise
    success_url = '/exercises'

def add_completion(request, exercise_id):
    form = CompletionForm(request.POST)
    if form.is_valid():
        new_completion = form.save(commit=False)
        new_completion.exercise_id = exercise_id
        new_completion.save()
    return redirect('exercise_details', exercise_id=exercise_id)

def add_photo(request, exercise_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, exercise_id=exercise_id)
        except Exception as e:
            print('An error occured uploading file to S3')
            print(e)
    return redirect('exercise_details', exercise_id=exercise_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>Exercise Tracker</h1>
<hr />
<p>
  We're here to help you achieve your fitness goals and live a healthier
  lifestyle. Our platform offers a range of tools and features to track your
  exercises, set goals, and monitor your progress. With our exercise logging
  feature, you can easily record your workouts, including exercise type,
  duration, intensity, and calories burned. This helps you maintain a detailed
  record and make informed decisions for your training. Setting goals is crucial
  for success. Our platform allows you to personalize your goals, whether it's
  weight loss, muscle gain, or running a marathon. We'll keep you on track by
  monitoring your progress and providing insights to keep you motivated.
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Exercise Tracker</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Exercise Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'exercises_index' %}">View All Exercises</a></li>
          <li><a href="{% url 'exercise_create' %}">Add An Exercise</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
{% block content %}
{% endblock %}
</main>
<footer class="page-footer">
  <div class="right">All Rights Reserved, &copy; 2021 Exercise Collector &nbsp;</div>
</footer>
</body>
</html>

main_app/templates/exercises/details.html
{% extends 'base.html' %} {% block content %}

<h1>{{ exercise.name }}</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <p>Muscle Group: {{ exercise.musclegroups }}</p>
        <p>Intensity: {{ exercise.intensity }}</p>
        <p>Directions: {{ exercise.directions }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'exercise_update' exercise.id %}">Edit</a>
        <a href="{% url 'exercise_delete' exercise.id %}">Delete</a>
      </div>
    </div>
    {% for photo in exercise.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' exercise.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <button type="submit" class="btn">Upload Photo</button>
  </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_completion' exercise.id %}" method="POST">
      {% csrf_token %} {{completion_form.as_p}}
      <input type="submit" class="btn" value="Add Record" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Reps</th>
          <th>Sets</th>
        </tr>
      </thead>
      <tbody>
        {% for completion in exercise.completion_set.all %}
        <tr>
          <td>{{completion.date}}</td>
          <td>{{completion.reps}}</td>
          <td>{{completion.sets}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  const dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
</script>

{% endblock %}

main_app/templates/exercises/index.html
{% extends 'base.html' %} {% block content %} {% for exercise in exercises %}
<a href="{% url 'exercise_details' exercise.id %}">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ exercise.name }}</span>
    <p>Muscle Group: {{ exercise.musclegroups }}</p>
    <p>Intensity: {{ exercise.intensity }}</p>
    <p>Directions: {{ exercise.directions }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'exercise_update' exercise.id %}">Edit</a>
    <a href="{% url 'exercise_delete' exercise.id %}">Delete</a>
  </div>
</div>
</a>

{% endfor %} {% endblock %}

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Exercise Tracker</title>
  </head>
  <body>
    <h1>Home</h1>
  </body>
</html>

main_app/templates/main_app/exercise_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Exercise</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'exercises_index' %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/exercise_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Add Exercise</h1>
{% endif %}

<form action="" method="POST">
  <!-- Security token -->
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}